//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DonHangCTs = new HashSet<DonHangCT>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public int HinhThucTT { get; set; }
        public Nullable<int> IdTK { get; set; }
        public System.DateTime NgayDat { get; set; }
        public int TinhTrang { get; set; }
        public string DiaChiNhanHang { get; set; }
        public string SDT { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangCT> DonHangCTs { get; set; }
    }
}
